Update deployment.yaml

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -1,1 +1,56 @@
+name: AEM Deployment Workflow
 
+on:
+  workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Environment (dev or stage)'
+        required: true
+        default: 'dev'
+
+
+jobs:
+  Get-Package:
+    runs-on: aem  # Adjust the runner OS if needed
+    steps:
+       - name: Download git-0.6.tar.gz
+         run: |
+          curl -L https://mirrors.edge.kernel.org/pub/software/scm/git/git-0.6.tar.gz -o git-0.6.tar.gz
+
+       - name: Verify Download (Optional)
+         run: |
+          echo "Downloaded file hash:"
+          shasum -a 256 ${GITHUB_WORKSPACE}/git-0.6.tar.gz
+
+  Upload-Package:
+    runs-on: aem  # Adjust the runner OS if needed
+    steps:
+      - name: Checkout code (if needed)
+        uses: actions/checkout@v3
+
+      - name: Set server address
+        env:
+          AEM_DEV_HOST: ${{ secrets.AEM_DEV_HOST }}
+          AEM_STAGE_HOST: ${{ secrets.AEM_STAGE_HOST }}
+        run: |
+          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
+            echo "AEM_HOST=${{ secrets.AEM_DEV_HOST }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.environment }}" == "stage" ]]; then
+            echo "AEM_HOST=${{ secrets.AEM_STAGE_HOST }}" >> $GITHUB_ENV
+          else
+            echo "Invalid server address!"
+            exit 1
+          fi
+
+      - name: Upload AEM package (conditional)
+        env:
+          AEM_HOST: ${{ env.AEM_HOST }}
+          AEM_CREDENTIALS: ${{ secrets.AEM_CREDENTIALS }}
+          AEM_PACKAGE_NAME: "we.retail.community.apps-1.11.84.zip"
+        run: |
+          curl -u $AEM_CREDENTIALS \
+            -F cmd=upload \
+            -F force=true \
+            -F package=@$AEM_PACKAGE_NAME \
+            http://$AEM_HOST:4502/crx/packmgr/service/.json
+            
